<?php

namespace Pequiven\MasterBundle\Repository\ArrangementProgram;

use Pequiven\ArrangementProgramBundle\Entity\ArrangementProgram;
use Pequiven\SEIPBundle\Entity\Period;
use Pequiven\SEIPBundle\Entity\User;
use Pequiven\SEIPBundle\Doctrine\ORM\SeipEntityRepository as EntityRepository;

/**
 * Repositorio de Categoría de programa de gestion (pequiven.repository.category_arrangementprogram)
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryArrangementProgramRepository extends EntityRepository
{
    
}