<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace Pequiven\MasterBundle\Model;

use Doctrine\ORM\Mapping as ORM;

/**
 * Description of GerenciaSecond
 *
 * @author matias
 */
abstract class GerenciaSecond {

    //Morón-Gerencia General
    const REF_GERENCIA_PRODUCCION_CPM = 1; //MODULAR
    const REF_GERENCIA_MANTENIMIENTO_CPM = 2; //MODULAR
    const REF_GERENCIA_SERV_GENERALES_CPM = 3; //MODULAR
    const REF_GERENCIA_MODULAR_SHA_CPM = 4; //MODULAR
    const REF_GERENCIA_MODULAR_DESARROLLO_SOCIAL_CPM = 5; //MODULAR
    const REF_GERENCIA_TECNICA_CPM = 6; //MODULAR
    const REF_GERENCIA_SUMINISTRO_CPM = 7; //MODULAR
    const REF_GERENCIA_MATERIALES_BARIVEN_CPM = 8; //MODULAR
    const REF_GERENCIA_PROYECTOS_TRONCAL_III_VIA_PERIMETRAL = 9; //MODULAR
    //Morón-UNFER
    const REF_GERENCIA_PLANIFICACION_COMERCIAL_UNFER = 10;
    const REF_GERENCIA_ABASTECIMIENTO_FERTILIZANTES_UNFER = 11;
    const REF_GERENCIA_FINANZAS_UNFER = 12;
    //Morón-UNPI
    const REF_GERENCIA_PLANIFICACION_GESTION_Y_CONTROL_UNPI = 13;
    const REF_GERENCIA_VENTAS_NACIONALES_Y_MERCADEO_UNPI_CPJAA = 14;
    const REF_GERENCIA_PLANTA_DIST_TERMINAL_BORBURATA_UNPI_CPJAA = 15;
    //Morón-Proyectos Morón
    const REF_GERENCIA_PROYECTO_FOSFATADO_MORON = 16;
    const REF_GERENCIA_ARRANQUE_FOSFATADOS_NUEVAS_PLANTAS = 17;
    const REF_GERENCIA_PROYECTO_NITROGENADO_MORON = 18;
    const REF_GERENCIA_ARRANQUE_NITROGENADOS_NUEVAS_PLANTAS = 19;
    const REF_GERENCIA_INFRAESTRUCTURA_Y_SERVICIOS = 20;
    //Morón-Logística Comercial
    const REF_GERENCIA_OPERAC_PROTUARIAS_ENSACADO_Y_MEZCLADO = 21;
    const REF_GERENCIA_DISTRIBUCION_Y_TRANSPORTE = 22;
    //Morón-IPSL/Comercio Exterior
    const REF_GERENCIA_COMERCIAL_FERTILIZANTES = 23;
    const REF_GERENCIA_COMERCIAL = 24;
    const REF_GERENCIA_COMERCIAL_PRODUCTOS = 25;
    const REF_GERENCIA_ADMINISTRACION_Y_FINANZAS = 26;
    const REF_GERENCIA_LOGISTICA = 27;
    const REF_GERENCIA_PLANIFICACION_E_INTELIGENCIA_DE_MERC = 28;
    //AMC-Gerencia General
    const REF_GERENCIA_PRODUCCION_CPAMC = 29; //MODULAR
    const REF_GERENCIA_MANTENIMIENTO_CPAMC = 30; //MODULAR
    const REF_GERENCIA_TECNICA_CPAMC = 31; //MODULAR
    const REF_GERENCIA_SERV_GENERALES_CPAMC = 32; //MODULAR
    const REF_GERENCIA_SUMINISTRO_CPAMC = 33; //MODULAR
    const REF_GERENCIA_MODULAR_SHA_CPAMC = 34; //MODULAR
    const REF_GERENCIA_MODULAR_REGIONAL_DESARROLLO_INTEGRAL_COMUNITARIO_CPAMC = 35; //MODULAR
    const REF_GERENCIA_PROYECTOS_OPERACIONALES = 36; //MODULAR
    const REF_GERENCIA_MATERIALES_CPAMC = 37; //MODULAR
    //AMC-UNOP
    const REF_GERENCIA_MERCADEO_Y_VENTAS_UNOP = 38;
    const REF_GERENCIA_PLANIFICACION_UNOP = 39;
    //JAA-Gerencia General
    const REF_GERENCIA_PRODUCCION_CPJAA = 40; //MODULAR
    const REF_GERENCIA_MANTENIMIENTO_CPJAA = 41; //MODULAR
    const REF_GERENCIA_SERV_GENERALES_CPJAA = 42; //MODULAR
    const REF_GERENCIA_TECNICA_Y_PROYECTOS_OPERACIONALES_CPJAA = 43; //MODULAR
    const REF_GERENCIA_MATERIALES_CPJAA = 44; //MODULAR
    const REF_GERENCIA_MODULAR_SHA_CPJAA = 45; //MODULAR
    const REF_GERENCIA_MODULAR_REGIONAL_DESARROLLO_INTEGRAL_COMUNITARIO_CPJAA = 46; //MODULAR
    //Navay-Gerencia General
    const REF_GERENCIA_DESARROLLO_MINA_NAVAY = 47; //MODULAR
    const REF_GERENCIA_PLANTAS_Y_SERV_INDUSTRIALES_NAVAY = 48; //MODULAR
    const REF_GERENCIA_INFRAESTRUCTURA_NAVAY = 49; //MODULAR
    const REF_RELACIONES_CON_ENTORNO_NAVAY = 50; //MODULAR
    //ZIV-Estimación de Costos
    const REF_GERENCIA_ESTIMACION_COSTOS_CPM = 51; //VINCULANTE
    const REF_GERENCIA_ESTIMACION_COSTOS_CPAMC = 52; //VINCULANTE
    const REF_GERENCIA_ESTIMACION_COSTOS_CPJAA = 53; //VINCULANTE
    const REF_GERENCIA_ESTIMACION_COSTOS_ZIV = 54;
    //ZIV-Control Gestión Oficina Presidencia
    //ZIV-Transporte Aéreo
    //ZIV-Planificación Estratégica y Nvos. Desarrollos
    const REF_GERENCIA_PLANIFICACIÓN_ZIV = 55;
    const REF_GERENCIA_CONTROL_ESTADISTICO_E_INFORMACION_ZIV = 56;
    const REF_GERENCIA_ANALISIS_Y_EVALUACION_ECONOMICA_ZIV = 57;
    const REF_GERENCIA_INGENIERIA_ZIV = 58;
    const REF_COORDINACION_MORON = 147;
    const REF_COORDINACION_AMC = 148;
    const REF_COORDINACION_JAA = 149;
    //ZIV-Seg. Ctrol. Financiero/Admvo. Proyectos
    const REF_GERENCIA_PLANIFICACION_CONTROL_DE_GESTION = 59;
    const REF_GERENCIA_SERVICIOS_FINANCIEROS_PROYECTOS = 60;
    const REF_GERENCIA_EVAL_Y_CTROL_FINANC_ADMIN_PROYECTOS = 61;
    //ZIV-Proyectos Internacionales
    const REF_GERENCIA_RELAC_INSTITUCIONALES_Y_LOGISTICA = 62;
    const REF_GERENCIA_PLANIFICACION_Y_NUEVOS_DESARROLLOS = 63;
    const REF_GERENCIA_INGENIERIA_PROYECTOS_INTERNACIONALES = 64;
    //ZIV-Proyecto Terminal Marítimo
    const REF_GERENCIA_QA_QC = 65;
    const REF_GERENCIA_INGENIERIA_Y_CONSTRUCCION = 66;
    const REF_GERENCIA_ARRANQUE = 67;
    //ZIV-Recursos Humanos
    const REF_GERENCIA_PLANIFICACION_Y_CTROL_GESTION_RRHH_ZIV = 68;
    const REF_GERENCIA_SERVICIOS_ORGANIZACIONALES_RRHH_ZIV = 69;
    const REF_GERENCIA_PLANES_Y_BENEFICIOS_RRHH_ZIV = 70;
    const REF_GERENCIA_RELACIONES_LABORALES_RRHH_ZIV = 71;
    const REF_GERENCIA_CALIDAD_DE_VIDA_RRHH_ZIV = 72;
    const REF_GERENCIA_CAPET_RRHH_ZIV = 73;
    const REF_GERENCIA_RRHH_ZIV = 74;
    const REF_GERENCIA_RRHH_CPM = 75; //VINCULANTE
    const REF_GERENCIA_RRHH_CPAMC = 76; //VINCULANTE
    const REF_GERENCIA_RRHH_CPJAA = 77; //VINCULANTE
    //ZIV-Auditoria Interna
    const REF_GERENCIA_AUDITORIA_OLEFINAS_Y_PLASTICOS_ZIV = 78;
    const REF_GERENCIA_AUDITORIA_FERTILIZANTES_ZIV = 79;
    const REF_GERENCIA_AUDITORIA_PROC_IND_Y_PROC_CORP_ZIV = 80;
    const REF_GERENCIA_AUDITORIA_PROYECTOS_ZIV = 81;
    const REF_GERENCIA_DETERMINACION_DE_RESPONSABILIDADES_ZIV = 82;
    //ZIV-Consultoria Jurídica y Rpte. Judicial
    const REF_GERENCIA_ASUNTOS_LEGALES_PROYECTOS_ZIV = 83;
    const REF_GERENCIA_ASUNTOS_LEGALES_NACIONALES_ZIV = 84;
    const REF_GERENCIA_ASUNTOS_LEGALES_INTERNACIONALES_ZIV = 85;
    const REF_GERENCIA_LITIGIOS_Y_RECLAMOS_ZIV = 86;
    const REF_GERENCIA_ASUNTOS_LEGALES_CPM = 87; //VINCULANTE
    const REF_GERENCIA_ASUNTOS_LEGALES_CPAMC = 88; //VINCULANTE
    const REF_GERENCIA_ASUNTOS_LEGALES_CPJAA = 89; //VINCULANTE
    //ZIV-Contrataciones
    const REF_GERENCIA_PROCURA_ZIV = 90;
    const REF_GERENCIA_CONTRATACIONES_ZIV = 91;
    //ZIV-Finanzas
    const REF_GERENCIA_SERVICIOS_FINANCIEROS_ZIV = 92;
    const REF_GERENCIA_PRESUPUESTOS_Y_COSTOS_ZIV = 93;
    const REF_GERENCIA_TRIBUTARIO_ZIV = 94;
    const REF_GERENCIA_TESORERIA_ZIV = 95;
    const REF_GERENCIA_CONTRALORIA_FINANCIERA = 96;
    const REF_GERENCIA_RIESGOS_Y_SEGUROS = 97;
    const REF_GERENCIA_FINANZAS_CPM = 98; //VINCULANTE
    const REF_GERENCIA_FINANZAS_CPAMC = 99; //VINCULANTE
    const REF_GERENCIA_FINANZAS_CPJAA = 100; //VINCULANTE
    //ZIV-AIT
    const REF_GERENCIA_INFRAESTRUCTURA_DE_TELECOMUNICACIONES_ZIV = 101;
    const REF_GERENCIA_SISTEMAS_Y_APLICACIONES_ZIV = 102;
    const REF_GERENCIA_PLANIFICACION_CONTROL_DE_GESTION_AIT_ZIV = 103;
    const REF_GERENCIA_INFRAESTRUCTURA_Y_OPERACIONES_ZIV = 104;
    const REF_GERENCIA_AIT_CPM = 105; //VINCULANTE
    const REF_GERENCIA_AIT_CPAMC = 106; //VINCULANTE
    const REF_GERENCIA_AIT_CPJAA = 107; //VINCULANTE
    //ZIV-PCP
    const REF_GERENCIA_INVESTIGACIONES_ZIV = 108;
    const REF_GERENCIA_OPERACIONES_ZIV = 109;
    const REF_GERENCIA_EMPRESAS_MIXTAS_Y_NVOS_PROYECTOS_ZIV = 110;
    const REF_GERENCIA_PROTECCION_EMPRESARIAL_ZIV = 111;
    const REF_GERENCIA_ADM_Y_CONTROL_DE_GESTION_ZIV = 112;
    const REF_GERENCIA_PREVENCION_ZIV = 113;
    const REF_GERENCIA_PCP_CPM = 114; //VINCULANTE
    const REF_GERENCIA_PCP_CPAMC = 115; //VINCULANTE
    const REF_GERENCIA_PCP_CPJAA = 116; //VINCULANTE
    //ZIV-Salud
    const REF_GERENCIA_SALUD_INTEGRAL_ZIV = 117;
    const REF_GERENCIA_SALUD_OPERACIONAL_ZIV = 118;
    const REF_GERENCIA_PLANIFICACION_Y_GESTION_SALUD_ZIV = 119;
    const REF_GERENCIA_SALUD_CPM = 120; //VINCULANTE
    const REF_GERENCIA_SALUD_CPAMC = 121; //VINCULANTE
    const REF_GERENCIA_SALUD_CPJAA = 122; //VINCULANTE
    //ZIV-Administración y Servicios
    const REF_GERENCIA_INFRAESTRUCTURA_ADM_Y_SERV_ZIV = 123;
    const REF_GERENCIA_APOYO_ADM_Y_SERV_ZIV = 124;
    //ZIV-Asuntos Públicos
    const REF_GERENCIA_RELACIONES_PUBLICAS_ZIV = 125;
    const REF_GERENCIA_COMUNICACIONES_ZIV = 126;
    const REF_GERENCIA_ORG_DE_EVENTOS_Y_PROTOCOLO_ZIV = 127;
    const REF_GERENCIA_ASUNTOS_PUBLICOS_CPM = 128; //VINCULANTE
    const REF_GERENCIA_ASUNTOS_PUBLICOS_CPAMC = 129; //VINCULANTE
    const REF_GERENCIA_ASUNTOS_PUBLICOS_CPJAA = 130; //VINCULANTE
    //ZIV-Desarrollo Social
    const REF_GERENCIA_DESARROLLO_SOCIAL_CPM = 131; //VINCULANTE
    const REF_GERENCIA_REGIONAL_DESARROLLO_INTEGRAL_COMUNITARIO_CPAMC = 132; //VINCULANTE
    const REF_GERENCIA_REGIONAL_DESARROLLO_INTEGRAL_COMUNITARIO_CPJAA = 133; //VINCULANTE
    //ZIV-SHA
    const REF_GERENCIA_PLANIFICACION_Y_CONTROL_DE_GESTION_SHA_ZIV = 134;
    const REF_GERENCIA_INGENIERIA_DE_RIESGO_ZIV = 135;
    const REF_GERENCIA_PREV_CONT_DE_EMERG_Y_CONTINGENCIA_ZIV = 136;
    const REF_GERENCIA_AMBIENTE_HIGIENE_OCUPACIONAL_ZIV = 137;
    const REF_GERENCIA_DISENO_SHA_ZIV = 138;
    const REF_GERENCIA_SHA_CPM = 139; //VINCULANTE
    const REF_GERENCIA_SHA_CPAMC = 140; //VINCULANTE
    const REF_GERENCIA_SHA_CPJAA = 141; //VINCULANTE
    //ZIV-SIG
    const REF_GERENCIA_ESTANDARIZACION_SIG_ZIV = 142;
    const REF_GERENCIA_MANTENIMIENTO_SIG_ZIV = 143;
    const REF_GERENCIA_MANTENIMIENTO_SIG_CPM = 144;
    const REF_GERENCIA_MANTENIMIENTO_SIG_CPAMC = 145;
    const REF_GERENCIA_MANTENIMIENTO_SIG_CPJAA = 146;

    protected $refName = array();

    /**
     * Tipo de gerencia modular
     */
    const TYPE_MANAGEMENT_MODULAR = 1;

    /**
     * Tipo de gerencia vinculante
     */
    const TYPE_MANAGEMENT_BINDING = 0;

    public function __construct() {
        //Morón
        $this->refName[self::REF_GERENCIA_PRODUCCION_CPM] = 'GERENCIA_PRODUCCION_CPM';
        $this->refName[self::REF_GERENCIA_MANTENIMIENTO_CPM] = 'GERENCIA_MANTENIMIENTO_CPM';
        $this->refName[self::REF_GERENCIA_SERV_GENERALES_CPM] = 'GERENCIA_SERV_GENERALES_CPM';
        $this->refName[self::REF_GERENCIA_MODULAR_SHA_CPM] = 'GERENCIA_MODULAR_SHA_CPM';
        $this->refName[self::REF_GERENCIA_MODULAR_DESARROLLO_SOCIAL_CPM] = 'GERENCIA_MODULAR_DESARROLLO_SOCIAL_CPM';
        $this->refName[self::REF_GERENCIA_TECNICA_CPM] = 'GERENCIA_TECNICA_CPM';
        $this->refName[self::REF_GERENCIA_SUMINISTRO_CPM] = 'GERENCIA_SUMINISTRO_CPM';
        $this->refName[self::REF_GERENCIA_MATERIALES_BARIVEN_CPM] = 'GERENCIA_MATERIALES_BARIVEN_CPM';
        $this->refName[self::REF_GERENCIA_PROYECTOS_TRONCAL_III_VIA_PERIMETRAL] = 'GERENCIA_PROYECTOS_TRONCAL_III_VIA_PERIMETRAL';
        $this->refName[self::REF_GERENCIA_PLANIFICACION_COMERCIAL_UNFER] = 'GERENCIA_PLANIFICACION_COMERCIAL_UNFER';
        $this->refName[self::REF_GERENCIA_ABASTECIMIENTO_FERTILIZANTES_UNFER] = 'GERENCIA_ABASTECIMIENTO_FERTILIZANTES_UNFER';
        $this->refName[self::REF_GERENCIA_FINANZAS_UNFER] = 'GERENCIA_FINANZAS_UNFER';
        $this->refName[self::REF_GERENCIA_PLANIFICACION_GESTION_Y_CONTROL_UNPI] = 'GERENCIA_PLANIFICACION_GESTION_Y_CONTROL_UNPI';
        $this->refName[self::REF_GERENCIA_VENTAS_NACIONALES_Y_MERCADEO_UNPI_CPJAA] = 'GERENCIA_VENTAS_NACIONALES_Y_MERCADEO_UNPI';
        $this->refName[self::REF_GERENCIA_PLANTA_DIST_TERMINAL_BORBURATA_UNPI_CPJAA] = 'GERENCIA_PLANTA_DIST_TERMINAL_BORBURATA_UNPI';
        $this->refName[self::REF_GERENCIA_PROYECTO_FOSFATADO_MORON] = 'GERENCIA_PROYECTO_FOSFATADO_MORON';
        $this->refName[self::REF_GERENCIA_ARRANQUE_FOSFATADOS_NUEVAS_PLANTAS] = 'GERENCIA_ARRANQUE_FOSFATADOS_NUEVAS_PLANTAS';
        $this->refName[self::REF_GERENCIA_PROYECTO_NITROGENADO_MORON] = 'GERENCIA_PROYECTO_NITROGENADO_MORON';
        $this->refName[self::REF_GERENCIA_ARRANQUE_NITROGENADOS_NUEVAS_PLANTAS] = 'GERENCIA_ARRANQUE_NITROGENADOS_NUEVAS_PLANTAS';
        $this->refName[self::REF_GERENCIA_INFRAESTRUCTURA_Y_SERVICIOS] = 'GERENCIA_INFRAESTRUCTURA_Y_SERVICIOS';
        $this->refName[self::REF_GERENCIA_OPERAC_PROTUARIAS_ENSACADO_Y_MEZCLADO] = 'GERENCIA_OPERAC_PROTUARIAS_ENSACADO_Y_MEZCLADO';
        $this->refName[self::REF_GERENCIA_DISTRIBUCION_Y_TRANSPORTE] = 'GERENCIA_DISTRIBUCION_Y_TRANSPORTE';
        $this->refName[self::REF_GERENCIA_COMERCIAL_FERTILIZANTES] = 'GERENCIA_COMERCIAL_FERTILIZANTES';
        $this->refName[self::REF_GERENCIA_COMERCIAL] = 'GERENCIA_COMERCIAL';
        $this->refName[self::REF_GERENCIA_COMERCIAL_PRODUCTOS] = 'GERENCIA_COMERCIAL_PRODUCTOS';
        $this->refName[self::REF_GERENCIA_ADMINISTRACION_Y_FINANZAS] = 'GERENCIA_ADMINISTRACION_Y_FINANZAS';
        $this->refName[self::REF_GERENCIA_LOGISTICA] = 'GERENCIA_LOGISTICA';
        $this->refName[self::REF_GERENCIA_PLANIFICACION_E_INTELIGENCIA_DE_MERC] = 'GERENCIA_PLANIFICACION_E_INTELIGENCIA_DE_MERC';
        $this->refName[self::REF_GERENCIA_PRODUCCION_CPAMC] = 'GERENCIA_PRODUCCION_CPAMC';
        $this->refName[self::REF_GERENCIA_MANTENIMIENTO_CPAMC] = 'GERENCIA_MANTENIMIENTO_CPAMC';
        $this->refName[self::REF_GERENCIA_TECNICA_CPAMC] = 'GERENCIA_TECNICA_CPAMC';
        $this->refName[self::REF_GERENCIA_SERV_GENERALES_CPAMC] = 'GERENCIA_SERV_GENERALES_CPAMC';
        $this->refName[self::REF_GERENCIA_SUMINISTRO_CPAMC] = 'GERENCIA_SUMINISTRO_CPAMC';
        $this->refName[self::REF_GERENCIA_MODULAR_SHA_CPAMC] = 'GERENCIA_MODULAR_SHA_CPAMC';
        $this->refName[self::REF_GERENCIA_MODULAR_REGIONAL_DESARROLLO_INTEGRAL_COMUNITARIO_CPAMC] = 'GERENCIA_MODULAR_REGIONAL_DESARROLLO_INTEGRAL_COMUNITARIO_CPAMC';
        $this->refName[self::REF_GERENCIA_PROYECTOS_OPERACIONALES] = 'GERENCIA_PROYECTOS_OPERACIONALES';
        $this->refName[self::REF_GERENCIA_MATERIALES_CPAMC] = 'GERENCIA_MATERIALES_CPAMC';
        $this->refName[self::REF_GERENCIA_MERCADEO_Y_VENTAS_UNOP] = 'GERENCIA_MERCADEO_Y_VENTAS_UNOP';
        $this->refName[self::REF_GERENCIA_PLANIFICACION_UNOP] = 'GERENCIA_PLANIFICACION_UNOP';
        $this->refName[self::REF_GERENCIA_PRODUCCION_CPJAA] = 'GERENCIA_PRODUCCION_CPJAA';
        $this->refName[self::REF_GERENCIA_MANTENIMIENTO_CPJAA] = 'GERENCIA_MANTENIMIENTO_CPJAA';
        $this->refName[self::REF_GERENCIA_SERV_GENERALES_CPJAA] = 'GERENCIA_SERV_GENERALES_CPJAA';
        $this->refName[self::REF_GERENCIA_TECNICA_Y_PROYECTOS_OPERACIONALES_CPJAA] = 'GERENCIA_TECNICA_Y_PROYECTOS_OPERACIONALES_CPJAA';
        $this->refName[self::REF_GERENCIA_MATERIALES_CPJAA] = 'GERENCIA_MATERIALES_CPJAA';
        $this->refName[self::REF_GERENCIA_MODULAR_SHA_CPJAA] = 'GERENCIA_MODULAR_SHA_CPJAA';
        $this->refName[self::REF_GERENCIA_MODULAR_REGIONAL_DESARROLLO_INTEGRAL_COMUNITARIO_CPJAA] = 'GERENCIA_MODULAR_REGIONAL_DESARROLLO_INTEGRAL_COMUNITARIO_CPJAA';
        $this->refName[self::REF_GERENCIA_DESARROLLO_MINA_NAVAY] = 'GERENCIA_DESARROLLO_MINA_NAVAY';
        $this->refName[self::REF_GERENCIA_PLANTAS_Y_SERV_INDUSTRIALES_NAVAY] = 'GERENCIA_PLANTAS_Y_SERV_INDUSTRIALES_NAVAY';
        $this->refName[self::REF_GERENCIA_INFRAESTRUCTURA_NAVAY] = 'GERENCIA_INFRAESTRUCTURA_NAVAY';
        $this->refName[self::REF_RELACIONES_CON_ENTORNO_NAVAY] = 'RELACIONES_CON_ENTORNO_NAVAY';
        $this->refName[self::REF_GERENCIA_ESTIMACION_COSTOS_CPM] = 'GERENCIA_ESTIMACION_COSTOS_CPM';
        $this->refName[self::REF_GERENCIA_ESTIMACION_COSTOS_CPAMC] = 'GERENCIA_ESTIMACION_COSTOS_CPAMC';
        $this->refName[self::REF_GERENCIA_ESTIMACION_COSTOS_CPJAA] = 'GERENCIA_ESTIMACION_COSTOS_CPJAA';
        $this->refName[self::REF_GERENCIA_ESTIMACION_COSTOS_ZIV] = 'GERENCIA_ESTIMACION_COSTOS_ZIV';
        $this->refName[self::REF_GERENCIA_PLANIFICACIÓN_ZIV] = 'GERENCIA_PLANIFICACIÓN_ZIV';
        $this->refName[self::REF_GERENCIA_CONTROL_ESTADISTICO_E_INFORMACION_ZIV] = 'GERENCIA_CONTROL_ESTADISTICO_E_INFORMACION_ZIV';
        $this->refName[self::REF_GERENCIA_ANALISIS_Y_EVALUACION_ECONOMICA_ZIV] = 'GERENCIA_ANALISIS_Y_EVALUACION_ECONOMICA_ZIV';
        $this->refName[self::REF_GERENCIA_INGENIERIA_ZIV] = 'GERENCIA_INGENIERIA_ZIV';
        $this->refName[self::REF_GERENCIA_PLANIFICACION_CONTROL_DE_GESTION] = 'GERENCIA_PLANIFICACION_CONTROL_DE_GESTION';
        $this->refName[self::REF_GERENCIA_SERVICIOS_FINANCIEROS_PROYECTOS] = 'GERENCIA_SERVICIOS_FINANCIEROS_PROYECTOS';
        $this->refName[self::REF_GERENCIA_EVAL_Y_CTROL_FINANC_ADMIN_PROYECTOS] = 'GERENCIA_EVAL_Y_CTROL_FINANC_ADMIN_PROYECTOS';
        $this->refName[self::REF_GERENCIA_RELAC_INSTITUCIONALES_Y_LOGISTICA] = 'GERENCIA_RELAC_INSTITUCIONALES_Y_LOGISTICA';
        $this->refName[self::REF_GERENCIA_PLANIFICACION_Y_NUEVOS_DESARROLLOS] = 'GERENCIA_PLANIFICACION_Y_NUEVOS_DESARROLLOS';
        $this->refName[self::REF_GERENCIA_INGENIERIA_PROYECTOS_INTERNACIONALES] = 'GERENCIA_INGENIERIA_PROYECTOS_INTERNACIONALES';
        $this->refName[self::REF_GERENCIA_QA_QC] = 'GERENCIA_QA_QC';
        $this->refName[self::REF_GERENCIA_INGENIERIA_Y_CONSTRUCCION] = 'GERENCIA_INGENIERIA_Y_CONSTRUCCION';
        $this->refName[self::REF_GERENCIA_ARRANQUE] = 'GERENCIA_ARRANQUE';
        $this->refName[self::REF_GERENCIA_PLANIFICACION_Y_CTROL_GESTION_RRHH_ZIV] = 'GERENCIA_PLANIFICACION_Y_CTROL_GESTION_RRHH_ZIV';
        $this->refName[self::REF_GERENCIA_SERVICIOS_ORGANIZACIONALES_RRHH_ZIV] = 'GERENCIA_SERVICIOS_ORGANIZACIONALES_RRHH_ZIV';
        $this->refName[self::REF_GERENCIA_PLANES_Y_BENEFICIOS_RRHH_ZIV] = 'GERENCIA_PLANES_Y_BENEFICIOS_RRHH_ZIV';
        $this->refName[self::REF_GERENCIA_RELACIONES_LABORALES_RRHH_ZIV] = 'GERENCIA_RELACIONES_LABORALES_RRHH_ZIV';
        $this->refName[self::REF_GERENCIA_CALIDAD_DE_VIDA_RRHH_ZIV] = 'GERENCIA_CALIDAD_DE_VIDA_RRHH_ZIV';
        $this->refName[self::REF_GERENCIA_CAPET_RRHH_ZIV] = 'GERENCIA_CAPET_RRHH_ZIV';
        $this->refName[self::REF_GERENCIA_RRHH_ZIV] = 'GERENCIA_RRHH_ZIV';
        $this->refName[self::REF_GERENCIA_RRHH_CPM] = 'GERENCIA_RRHH_CPM';
        $this->refName[self::REF_GERENCIA_RRHH_CPAMC] = 'GERENCIA_RRHH_CPAMC';
        $this->refName[self::REF_GERENCIA_RRHH_CPJAA] = 'GERENCIA_RRHH_CPJAA';
        $this->refName[self::REF_GERENCIA_AUDITORIA_OLEFINAS_Y_PLASTICOS_ZIV] = 'GERENCIA_AUDITORIA_OLEFINAS_Y_PLASTICOS_ZIV';
        $this->refName[self::REF_GERENCIA_AUDITORIA_FERTILIZANTES_ZIV] = 'GERENCIA_AUDITORIA_FERTILIZANTES_ZIV';
        $this->refName[self::REF_GERENCIA_AUDITORIA_PROC_IND_Y_PROC_CORP_ZIV] = 'GERENCIA_AUDITORIA_PROC_IND_Y_PROC_CORP_ZIV';
        $this->refName[self::REF_GERENCIA_AUDITORIA_PROYECTOS_ZIV] = 'GERENCIA_AUDITORIA_PROYECTOS_ZIV';
        $this->refName[self::REF_GERENCIA_DETERMINACION_DE_RESPONSABILIDADES_ZIV] = 'GERENCIA_DETERMINACION_DE_RESPONSABILIDADES_ZIV';
        $this->refName[self::REF_GERENCIA_ASUNTOS_LEGALES_PROYECTOS_ZIV] = 'GERENCIA_ASUNTOS_LEGALES_PROYECTOS_ZIV';
        $this->refName[self::REF_GERENCIA_ASUNTOS_LEGALES_NACIONALES_ZIV] = 'GERENCIA_ASUNTOS_LEGALES_NACIONALES_ZIV';
        $this->refName[self::REF_GERENCIA_ASUNTOS_LEGALES_INTERNACIONALES_ZIV] = 'GERENCIA_ASUNTOS_LEGALES_INTERNACIONALES_ZIV';
        $this->refName[self::REF_GERENCIA_LITIGIOS_Y_RECLAMOS_ZIV] = 'GERENCIA_LITIGIOS_Y_RECLAMOS_ZIV';
        $this->refName[self::REF_GERENCIA_ASUNTOS_LEGALES_CPM] = 'GERENCIA_ASUNTOS_LEGALES_CPM';
        $this->refName[self::REF_GERENCIA_ASUNTOS_LEGALES_CPAMC] = 'GERENCIA_ASUNTOS_LEGALES_CPAMC';
        $this->refName[self::REF_GERENCIA_ASUNTOS_LEGALES_CPJAA] = 'GERENCIA_ASUNTOS_LEGALES_CPJAA';
        $this->refName[self::REF_GERENCIA_PROCURA_ZIV] = 'GERENCIA_PROCURA_ZIV';
        $this->refName[self::REF_GERENCIA_CONTRATACIONES_ZIV] = 'GERENCIA_CONTRATACIONES_ZIV';
        $this->refName[self::REF_GERENCIA_SERVICIOS_FINANCIEROS_ZIV] = 'GERENCIA_SERVICIOS_FINANCIEROS_ZIV';
        $this->refName[self::REF_GERENCIA_PRESUPUESTOS_Y_COSTOS_ZIV] = 'GERENCIA_PRESUPUESTOS_Y_COSTOS_ZIV';
        $this->refName[self::REF_GERENCIA_TRIBUTARIO_ZIV] = 'GERENCIA_TRIBUTARIO_ZIV';
        $this->refName[self::REF_GERENCIA_TESORERIA_ZIV] = 'GERENCIA_TESORERIA_ZIV';
        $this->refName[self::REF_GERENCIA_CONTRALORIA_FINANCIERA] = 'GERENCIA_CONTRALORIA_FINANCIERA';
        $this->refName[self::REF_GERENCIA_RIESGOS_Y_SEGUROS] = 'GERENCIA_RIESGOS_Y_SEGUROS';
        $this->refName[self::REF_GERENCIA_FINANZAS_CPM] = 'GERENCIA_FINANZAS_CPM';
        $this->refName[self::REF_GERENCIA_FINANZAS_CPAMC] = 'GERENCIA_FINANZAS_CPAMC';
        $this->refName[self::REF_GERENCIA_FINANZAS_CPJAA] = 'GERENCIA_FINANZAS_CPJAA';
        $this->refName[self::REF_GERENCIA_INFRAESTRUCTURA_DE_TELECOMUNICACIONES_ZIV] = 'GERENCIA_INFRAESTRUCTURA_DE_TELECOMUNICACIONES_ZIV';
        $this->refName[self::REF_GERENCIA_SISTEMAS_Y_APLICACIONES_ZIV] = 'GERENCIA_SISTEMAS_Y_APLICACIONES_ZIV';
        $this->refName[self::REF_GERENCIA_PLANIFICACION_CONTROL_DE_GESTION_AIT_ZIV] = 'GERENCIA_PLANIFICACION_CONTROL_DE_GESTION_AIT_ZIV';
        $this->refName[self::REF_GERENCIA_INFRAESTRUCTURA_Y_OPERACIONES_ZIV] = 'GERENCIA_INFRAESTRUCTURA_Y_OPERACIONES_ZIV';
        $this->refName[self::REF_GERENCIA_AIT_CPM] = 'GERENCIA_AIT_CPM';
        $this->refName[self::REF_GERENCIA_AIT_CPAMC] = 'GERENCIA_AIT_CPAMC';
        $this->refName[self::REF_GERENCIA_AIT_CPJAA] = 'GERENCIA_AIT_CPJAA';
        $this->refName[self::REF_GERENCIA_INVESTIGACIONES_ZIV] = 'GERENCIA_INVESTIGACIONES_ZIV';
        $this->refName[self::REF_GERENCIA_OPERACIONES_ZIV] = 'GERENCIA_OPERACIONES_ZIV';
        $this->refName[self::REF_GERENCIA_EMPRESAS_MIXTAS_Y_NVOS_PROYECTOS_ZIV] = 'GERENCIA_EMPRESAS_MIXTAS_Y_NVOS_PROYECTOS_ZIV';
        $this->refName[self::REF_GERENCIA_PROTECCION_EMPRESARIAL_ZIV] = 'GERENCIA_PROTECCION_EMPRESARIAL_ZIV';
        $this->refName[self::REF_GERENCIA_ADM_Y_CONTROL_DE_GESTION_ZIV] = 'GERENCIA_ADM_Y_CONTROL_DE_GESTION_ZIV';
        $this->refName[self::REF_GERENCIA_PREVENCION_ZIV] = 'GERENCIA_PREVENCION_ZIV';
        $this->refName[self::REF_GERENCIA_PCP_CPM] = 'GERENCIA_PCP_CPM';
        $this->refName[self::REF_GERENCIA_PCP_CPAMC] = 'GERENCIA_PCP_CPAMC';
        $this->refName[self::REF_GERENCIA_PCP_CPJAA] = 'GERENCIA_PCP_CPJAA';
        $this->refName[self::REF_GERENCIA_SALUD_INTEGRAL_ZIV] = 'GERENCIA_SALUD_INTEGRAL_ZIV';
        $this->refName[self::REF_GERENCIA_SALUD_OPERACIONAL_ZIV] = 'GERENCIA_SALUD_OPERACIONAL_ZIV';
        $this->refName[self::REF_GERENCIA_PLANIFICACION_Y_GESTION_SALUD_ZIV] = 'GERENCIA_PLANIFICACION_Y_GESTION_SALUD_ZIV';
        $this->refName[self::REF_GERENCIA_SALUD_CPM] = 'GERENCIA_SALUD_CPM';
        $this->refName[self::REF_GERENCIA_SALUD_CPAMC] = 'GERENCIA_SALUD_CPAMC';
        $this->refName[self::REF_GERENCIA_SALUD_CPJAA] = 'GERENCIA_SALUD_CPJAA';
        $this->refName[self::REF_GERENCIA_INFRAESTRUCTURA_ADM_Y_SERV_ZIV] = 'GERENCIA_INFRAESTRUCTURA_ADM_Y_SERV_ZIV';
        $this->refName[self::REF_GERENCIA_APOYO_ADM_Y_SERV_ZIV] = 'GERENCIA_APOYO_ADM_Y_SERV_ZIV';
        $this->refName[self::REF_GERENCIA_RELACIONES_PUBLICAS_ZIV] = 'GERENCIA_RELACIONES_PUBLICAS_ZIV';
        $this->refName[self::REF_GERENCIA_COMUNICACIONES_ZIV] = 'GERENCIA_COMUNICACIONES_ZIV';
        $this->refName[self::REF_GERENCIA_ORG_DE_EVENTOS_Y_PROTOCOLO_ZIV] = 'GERENCIA_ORG_DE_EVENTOS_Y_PROTOCOLO_ZIV';
        $this->refName[self::REF_GERENCIA_ASUNTOS_PUBLICOS_CPM] = 'GERENCIA_ASUNTOS_PUBLICOS_CPM';
        $this->refName[self::REF_GERENCIA_ASUNTOS_PUBLICOS_CPAMC] = 'GERENCIA_ASUNTOS_PUBLICOS_CPAMC';
        $this->refName[self::REF_GERENCIA_ASUNTOS_PUBLICOS_CPJAA] = 'GERENCIA_ASUNTOS_PUBLICOS_CPJAA';
        $this->refName[self::REF_GERENCIA_DESARROLLO_SOCIAL_CPM] = 'GERENCIA_DESARROLLO_SOCIAL_CPM';
        $this->refName[self::REF_GERENCIA_REGIONAL_DESARROLLO_INTEGRAL_COMUNITARIO_CPAMC] = 'GERENCIA_REGIONAL_DESARROLLO_INTEGRAL_COMUNITARIO_CPAMC';
        $this->refName[self::REF_GERENCIA_REGIONAL_DESARROLLO_INTEGRAL_COMUNITARIO_CPJAA] = 'GERENCIA_REGIONAL_DESARROLLO_INTEGRAL_COMUNITARIO_CPJAA';
        $this->refName[self::REF_GERENCIA_PLANIFICACION_Y_CONTROL_DE_GESTION_SHA_ZIV] = 'GERENCIA_PLANIFICACION_Y_CONTROL_DE_GESTION_SHA_ZIV';
        $this->refName[self::REF_GERENCIA_INGENIERIA_DE_RIESGO_ZIV] = 'GERENCIA_INGENIERIA_DE_RIESGO_ZIV';
        $this->refName[self::REF_GERENCIA_PREV_CONT_DE_EMERG_Y_CONTINGENCIA_ZIV] = 'GERENCIA_PREV_CONT_DE_EMERG_Y_CONTINGENCIA_ZIV';
        $this->refName[self::REF_GERENCIA_AMBIENTE_HIGIENE_OCUPACIONAL_ZIV] = 'GERENCIA_AMBIENTE_HIGIENE_OCUPACIONAL_ZIV';
        $this->refName[self::REF_GERENCIA_DISENO_SHA_ZIV] = 'GERENCIA_DISENO_SHA_ZIV';
        $this->refName[self::REF_GERENCIA_SHA_CPM] = 'GERENCIA_SHA_CPM';
        $this->refName[self::REF_GERENCIA_SHA_CPAMC] = 'GERENCIA_SHA_CPAMC';
        $this->refName[self::REF_GERENCIA_SHA_CPJAA] = 'GERENCIA_SHA_CPJAA';
        $this->refName[self::REF_GERENCIA_ESTANDARIZACION_SIG_ZIV] = 'GERENCIA_ESTANDARIZACION_SIG_ZIV';
        $this->refName[self::REF_GERENCIA_MANTENIMIENTO_SIG_ZIV] = 'GERENCIA_MANTENIMIENTO_SIG_ZIV';
        $this->refName[self::REF_GERENCIA_MANTENIMIENTO_SIG_CPM] = 'GERENCIA_MANTENIMIENTO_SIG_CPM';
        $this->refName[self::REF_GERENCIA_MANTENIMIENTO_SIG_CPAMC] = 'GERENCIA_MANTENIMIENTO_SIG_CPAMC';
        $this->refName[self::REF_GERENCIA_MANTENIMIENTO_SIG_CPJAA] = 'GERENCIA_MANTENIMIENTO_SIG_CPJAA';
        $this->refName[self::REF_COORDINACION_MORON] = 'COORDINACION_MORON';
        $this->refName[self::REF_COORDINACION_AMC] = 'COORDINACION_AMC';
        $this->refName[self::REF_COORDINACION_JAA] = 'COORDINACION_JAA';
    }

    /**
     * Retorna todas las referencias o códigos de las gerencias de 2da línea
     * @return type
     */
    public function getRefNameArray() {
        return $this->refName;
    }

    public function __toString() {
        return $this->description ? : '-';
    }

    static function getTypesManagement() {
        static $typeManagement = array(
            self::TYPE_MANAGEMENT_MODULAR => 'pequiven.arrangement_program.type_management.modular',
            self::TYPE_MANAGEMENT_BINDING => 'pequiven.arrangement_program.type_management.binding',
        );
        return $typeManagement;
    }

    /**
     * Retorna true si la gerencia le reporta a la corporativa y la de complejo
     * 
     * @return boolean
     */
    final public function isMedularAndBinding() {
        $valid = false;

        if ($this->modular && $this->vinculante) {
            $valid = true;
        }

        return $valid;
    }

}
