<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace Pequiven\MasterBundle\Model;

/**
 * Description of Gerencia
 *
 * @author matias
 */
class Gerencia {
    
    const GERENCIA_REF_CONSULTORIA_JURIDICA = 1;
    const GERENCIA_REF_PROYECTOS = 2;
    const GERENCIA_REF_RECURSOS_HUMANOS = 3;
    const GERENCIA_REF_ESTIMACION_COSTOS = 4;
    const GERENCIA_REF_PCP = 5;
    const GERENCIA_REF_AIT = 6;
    const GERENCIA_REF_ASUNTOS_PUBLICOS = 7;
    const GERENCIA_REF_FINANZAS = 8;
    const GERENCIA_REF_SALUD = 9;
    const GERENCIA_REF_SHA = 10;
    const GERENCIA_REF_SIG = 11;
    const GERENCIA_REF_MANTENIMIENTO = 12;
    const GERENCIA_REF_MATERIALES = 13;
    const GERENCIA_REF_PRODUCCION = 14;
    const GERENCIA_REF_SERVICIOS_GENERALES = 15;
    const GERENCIA_REF_SUMINISTRO = 16;
    const GERENCIA_REF_TECNICA = 17;
    const GERENCIA_REF_UNPI = 18;
    const GERENCIA_REF_PERSONAL_ASIGNADO = 19;
    const GERENCIA_REF_PLANIFICACION_ESTRATEGICA_NUEVOS_DESARROLLOS = 20;
    const GERENCIA_REF_CONTRATACIONES = 21;
    const GERENCIA_REF_AUDITORIA_INTERNA = 22;
    const GERENCIA_REF_ADMINISTRACION_SERVICIOS = 23;
    const GERENCIA_REF_COORD_DESARROLLO_SOCIAL_MORON = 24;
    const GERENCIA_REF_GENERAL_COMPLEJO_MORON = 25;
    const GERENCIA_REF_UCFER = 26;
    const GERENCIA_REF_PROYECTOS_OPERACIONALES = 27;
    const GERENCIA_REF_GENERAL_COMPLEJO_AMC = 28;
    const GERENCIA_REF_REG_DESARROLLO_INTEG_COMUNITARIO_AMC = 29;
    const GERENCIA_REF_UNOP = 30;
    const GERENCIA_REF_GENERAL_COMPLEJO_JAA = 31;
    const GERENCIA_REF_REG_DESARROLLO_INTEG_COMUNITARIO_JAA = 32;
    const GERENCIA_REF_TECNICA_PROYECTOS_OPERACIONALES = 33;
    const GERENCIA_REF_CONTROL_GESTION_OFIC_PRESIDENCIA = 34;
    const GERENCIA_REF_DESARROLLO_SOCIAL_OFIC_PRINCIPAL = 35;
    const GERENCIA_REF_TRANSPORTE_AEREO = 36;
    const GERENCIA_REF_JUNTA_DIRECTIVA = 37;
    const GERENCIA_REF_OFICINA_PRESIDENCIA = 38;
    const GERENCIA_REF_PROYECTO_TERMINAL_MARITIMO = 39;
    
    public $refName = array();
    
    public function __construct() {
        $this->refName[self::GERENCIA_REF_CONSULTORIA_JURIDICA] = 'GERENCIA_REF_CONSULTORIA_JURIDICA';
        $this->refName[self::GERENCIA_REF_PROYECTOS] = 'GERENCIA_REF_PROYECTOS';
        $this->refName[self::GERENCIA_REF_RECURSOS_HUMANOS] = 'GERENCIA_REF_RECURSOS_HUMANOS';
        $this->refName[self::GERENCIA_REF_ESTIMACION_COSTOS] = 'GERENCIA_REF_ESTIMACION_COSTOS';
        $this->refName[self::GERENCIA_REF_PCP] = 'GERENCIA_REF_PCP';
        $this->refName[self::GERENCIA_REF_AIT] = 'GERENCIA_REF_AIT';
        $this->refName[self::GERENCIA_REF_ASUNTOS_PUBLICOS] = 'GERENCIA_REF_ASUNTOS_PUBLICOS';
        $this->refName[self::GERENCIA_REF_FINANZAS] = 'GERENCIA_REF_FINANZAS';
        $this->refName[self::GERENCIA_REF_SALUD] = 'GERENCIA_REF_SALUD';
        $this->refName[self::GERENCIA_REF_SHA] = 'GERENCIA_REF_SHA';
        $this->refName[self::GERENCIA_REF_SIG] = 'GERENCIA_REF_SIG';
        $this->refName[self::GERENCIA_REF_MANTENIMIENTO] = 'GERENCIA_REF_MANTENIMIENTO';
        $this->refName[self::GERENCIA_REF_MATERIALES] = 'GERENCIA_REF_MATERIALES';
        $this->refName[self::GERENCIA_REF_PRODUCCION] = 'GERENCIA_REF_PRODUCCION';
        $this->refName[self::GERENCIA_REF_SERVICIOS_GENERALES] = 'GERENCIA_REF_SERVICIOS_GENERALES';
        $this->refName[self::GERENCIA_REF_SUMINISTRO] = 'GERENCIA_REF_SUMINISTRO';
        $this->refName[self::GERENCIA_REF_TECNICA] = 'GERENCIA_REF_TECNICA';
        $this->refName[self::GERENCIA_REF_UNPI] = 'GERENCIA_REF_UNPI';
        $this->refName[self::GERENCIA_REF_PERSONAL_ASIGNADO] = 'GERENCIA_REF_PERSONAL_ASIGNADO';
        $this->refName[self::GERENCIA_REF_PLANIFICACION_ESTRATEGICA_NUEVOS_DESARROLLOS] = 'GERENCIA_REF_PLANIFICACION_ESTRATEGICA_NUEVOS_DESARROLLOS';
        $this->refName[self::GERENCIA_REF_CONTRATACIONES] = 'GERENCIA_REF_CONTRATACIONES';
        $this->refName[self::GERENCIA_REF_AUDITORIA_INTERNA] = 'GERENCIA_REF_AUDITORIA_INTERNA';
        $this->refName[self::GERENCIA_REF_ADMINISTRACION_SERVICIOS] = 'GERENCIA_REF_ADMINISTRACION_SERVICIOS';
        $this->refName[self::GERENCIA_REF_COORD_DESARROLLO_SOCIAL_MORON] = 'GERENCIA_REF_COORD_DESARROLLO_SOCIAL_MORON';
        $this->refName[self::GERENCIA_REF_GENERAL_COMPLEJO_MORON] = 'GERENCIA_REF_GENERAL_COMPLEJO_MORON';
        $this->refName[self::GERENCIA_REF_UCFER] = 'GERENCIA_REF_UCFER';
        $this->refName[self::GERENCIA_REF_PROYECTOS_OPERACIONALES] = 'GERENCIA_REF_PROYECTOS_OPERACIONALES';
        $this->refName[self::GERENCIA_REF_GENERAL_COMPLEJO_AMC] = 'GERENCIA_REF_GENERAL_COMPLEJO_AMC';
        $this->refName[self::GERENCIA_REF_REG_DESARROLLO_INTEG_COMUNITARIO_AMC] = 'GERENCIA_REF_REG_DESARROLLO_INTEG_COMUNITARIO_AMC';
        $this->refName[self::GERENCIA_REF_UNOP] = 'GERENCIA_REF_UNOP';
        $this->refName[self::GERENCIA_REF_GENERAL_COMPLEJO_JAA] = 'GERENCIA_REF_GENERAL_COMPLEJO_JAA';
        $this->refName[self::GERENCIA_REF_REG_DESARROLLO_INTEG_COMUNITARIO_JAA] = 'GERENCIA_REF_REG_DESARROLLO_INTEG_COMUNITARIO_JAA';
        $this->refName[self::GERENCIA_REF_TECNICA_PROYECTOS_OPERACIONALES] = 'GERENCIA_REF_TECNICA_PROYECTOS_OPERACIONALES';
        $this->refName[self::GERENCIA_REF_CONTROL_GESTION_OFIC_PRESIDENCIA] = 'GERENCIA_REF_CONTROL_GESTION_OFIC_PRESIDENCIA';
        $this->refName[self::GERENCIA_REF_DESARROLLO_SOCIAL_OFIC_PRINCIPAL] = 'GERENCIA_REF_DESARROLLO_SOCIAL_OFIC_PRINCIPAL';
        $this->refName[self::GERENCIA_REF_TRANSPORTE_AEREO] = 'GERENCIA_REF_TRANSPORTE_AEREO';
        $this->refName[self::GERENCIA_REF_JUNTA_DIRECTIVA] = 'GERENCIA_REF_JUNTA_DIRECTIVA';
        $this->refName[self::GERENCIA_REF_OFICINA_PRESIDENCIA] = 'GERENCIA_REF_OFICINA_PRESIDENCIA';
        $this->refName[self::GERENCIA_REF_PROYECTO_TERMINAL_MARITIMO] = 'GERENCIA_REF_PROYECTO_TERMINAL_MARITIMO';
    }
    
    /**
     * Retorna todas las referencias o códigos de las gerencias de 1ra línea
     * @return type
     */
    public function getRefNameArray() {
        return $this->refName ;
    }
}
