<?php

namespace Pequiven\MasterBundle\Model;

use Doctrine\ORM\EntityRepository;

/**
 * RolRepository (pequiven.repository.rol)
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolRepository extends EntityRepository
{
}
