<?php

namespace Pequiven\SEIPBundle\Repository\HouseSupply\Inventory;

use Pequiven\SEIPBundle\Entity\Period;
use Pequiven\SEIPBundle\Entity\User;
use Pequiven\SEIPBundle\Doctrine\ORM\SeipEntityRepository as EntityRepository;

/**
 * Repositorio de MOVIMIENTO DE EMPLEADOS
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseSupplyProductRepository extends EntityRepository {

    function getAvailableProduct() {
        $qb = $this->getQueryBuilder();
        $qb
                ->innerJoin('HSprod.instance', 'inst')
                ->andWhere('inst.maxPerUser> :max')
                ->setParameter('max', 0)
        ;

//        print($qb->getQuery()->getSQL());
//        die();

        return $qb->getQuery()->getResult();
    }

    function getAlias() {
        return 'HSprod';
    }

}
