<?php

namespace Pequiven\SEIPBundle\Repository\HouseSupply\Inventory;

use Pequiven\SEIPBundle\Entity\Period;
use Pequiven\SEIPBundle\Entity\User;
use Pequiven\SEIPBundle\Doctrine\ORM\SeipEntityRepository as EntityRepository;

/**
 * Repositorio de MOVIMIENTO DE EMPLEADOS
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseSupplyInventoryChargeRepository extends EntityRepository {

    function FindLastInvChargeId() {
        $qb = $this->getQueryBuilder();
        $qb
                ->select('MAX(InvCharge.nroCharge)+1 as Id')
        ;
        // print($qb->getQuery()->getSQL());

        return $qb->getQuery()->getResult();
    }

    function FindNextInvChargeId() {
        $qb = $this->getQueryBuilder();
        $qb
                ->select('MAX(InvCharge.nroCharge)+1 as Id')
        ;
        // print($qb->getQuery()->getSQL());

        return $qb->getQuery()->getResult();
    }

    function getAlias() {
        return 'InvCharge';
    }

}
