<?php

namespace Pequiven\ArrangementProgramBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArrangementProgramRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArrangementProgramRepository extends EntityRepository
{
}
