<?php

namespace Pequiven\ArrangementProgramBundle\Repository;

use Pequiven\ArrangementProgramBundle\Entity\ChangeUserGoal;
use Pequiven\SEIPBundle\Entity\Period;
use Pequiven\SEIPBundle\Entity\User;
use Pequiven\SEIPBundle\Doctrine\ORM\SeipEntityRepository as EntityRepository;

/**
 * Repositorio de programa de gestion
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangeUserGoalRepository extends EntityRepository {
    
}
