<?php

namespace Pequiven\ArrangementProgramBundle\Repository;

use Pequiven\SEIPBundle\Entity\Period;
use Pequiven\SEIPBundle\Entity\User;
use Tecnocreaciones\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * GoalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoalRepository extends EntityRepository
{
    /**
     * Retorna las metas del usuario en los programa de gestion donde no es responsable
     * @param User $user
     * @param Period $period
     * @param array $criteria
     * @return type
     */
    function findGoalsByUserAndPeriod(User $user,Period $period,array $criteria = array())
    {
        $qb = $this->getQueryBuilder();
        $qb
            ->innerJoin('g.timeline', 't')
            ->innerJoin('t.arrangementProgram', 'ap')
            ->andWhere('ap.responsible != :responsible')
            ->andWhere('ap.period = :period')
            ->andWhere('g.responsible = :responsible')
            ->setParameter('period', $period)
            ->setParameter('responsible', $user)
            ;
        if(isset($criteria['notArrangementProgram'])){
            $qb->andWhere('ap.id != :arrangementProgram');
            $qb->setParameter('arrangementProgram', $criteria['notArrangementProgram']);
        }
        return $qb->getQuery()->getResult();
    }
    protected function getAlias() {
        return 'g';
    }
}
