<?php

namespace Pequiven\ArrangementProgramBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TimelineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimelineRepository extends EntityRepository
{
}
