<?php

namespace Pequiven\SEIPBundle\Repository;

use Tecnocreaciones\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * PeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodRepository extends EntityRepository
{
    function findOneActive()
    {
        return $this->findOneBy(array('status' => true));
    }
    
    protected function getAlias() {
        return "p";
    }
}
