pequiven_delivery_point_index:
    path: /.{_format}
    defaults:
        _controller: pequiven.controller.delivery_point:listAction
        _format: html
    requirements:
        _format: json|html
    methods: [GET]