pequiven_product_group_report_create:
    path: /{productGroup}/create
    defaults:
        _controller: pequiven.controller.product_report_delivery:createAction
        _sylius:
            form: pequiven_seipbundle_delivery_productreport
    methods: [GET|POST]
    
pequiven_product_report_delivery_update:
    path: /{id}/update
    defaults:
        _controller: pequiven.controller.product_report_delivery:updateAction
        _sylius:
            form: pequiven_seipbundle_delivery_productreport
    methods: [GET|POST|PUT]
    
pequiven_product_report_delivery_show:
    path: /{id}/show
    defaults:
        _controller: pequiven.controller.product_report_delivery:showAction
    methods: [GET|POST|PUT]


