<?php

namespace Pequiven\SEIPBundle\Repository\HouseSupply\Order;

use Pequiven\SEIPBundle\Entity\Period;
use Pequiven\SEIPBundle\Entity\User;
use Pequiven\SEIPBundle\Doctrine\ORM\SeipEntityRepository as EntityRepository;

/**
 * Repositorio de Ordenes HouseSupply
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseSupplyCycleRepository extends EntityRepository {

    function FinCycle($group, $date) {

        $qb = $this->getQueryBuilder();
        $qb
                ->andWhere('HSCycle.HouseSupplyCycleRepository= :group')
                ->andWhere('HSCycle.dateBeginOrder>= :date')
                ->andWhere('HSCycle.$dateEndOrder<= :date')
                ->setParameter('group', $group)
                ->setParameter('date', $date)
        ;

        //return $qb->getQuery()->getResult();
    }

    function getAlias() {
        return 'HSCycle';
    }

}
