<?php

namespace Pequiven\SEIPBundle\Repository\HouseSupply\Order;

use Pequiven\SEIPBundle\Entity\Period;
use Pequiven\SEIPBundle\Entity\User;
use Pequiven\SEIPBundle\Doctrine\ORM\SeipEntityRepository as EntityRepository;

/**
 * Repositorio de Ciclos de HouseSupply
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseSupplyCycleRepository extends EntityRepository {

    function FindCycle($date, $group = null) {

        $qb = $this->getQueryBuilder();
        $qb
                ->andWhere('HSCycle.dateBeginOrder <= :date')
                ->andWhere('HSCycle.dateEndOrder >= :date')
                ->setParameter('date', $date);
        if ($group != null) {
            $qb
                    ->andWhere('HSCycle.workStudyCircleGroup= :group')
                    ->setParameter('group', $group);
        }

        //var_dump($qb->getQuery()->getResult());
        //var_dump($date);
        //print($qb->getQuery()->getSQL());
        //die();

        return $qb->getQuery()->getResult();
    }

    function FindCycleBilling($date) {

        $qb = $this->getQueryBuilder();
        $qb
                ->andWhere('HSCycle.dateBeginOrder <= :date')
                ->andWhere('HSCycle.dateEndOrder >= :date')
                ->setParameter('date', $date)
        ;

//        var_dump($qb->getQuery()->getResult());
//        var_dump($date);
//        print($qb->getQuery()->getSQL());
//        die();

        return $qb->getQuery()->getResult();
    }

    function getAlias() {
        return 'HSCycle';
    }

}
