<?php

namespace Pequiven\ArrangementProgramBundle\Repository\MovementEmployee;

use Pequiven\ArrangementProgramBundle\Entity\ArrangementProgram;
use Pequiven\SEIPBundle\Entity\Period;
use Pequiven\SEIPBundle\Entity\User;
use Pequiven\ArrangementProgramBundle\Entity\Goal;
use Pequiven\SEIPBundle\Doctrine\ORM\SeipEntityRepository as EntityRepository;

/**
 * Repositorio de DETALLE DE MOVIMIENTO DE EMPLEADOS
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovementEmployeeRepository extends EntityRepository {

    function FindMovementbyGoal($idGoal, $period) {
        $qb = $this->getQueryBuilder();
        $qb
                ->Select('mov')
                ->andWhere('mov.Goal= :goals')
                ->andWhere('mov.period= :periodo')
                ->setParameter('goals', $idGoal)
                ->setParameter('periodo', $period)
        ;
        return $qb->getQuery()->getResult();
    }

    function getAlias() {
        return 'mov';
    }

}
