<?php

namespace Pequiven\ArrangementProgramBundle\Repository\MovementEmployee;

use Pequiven\ArrangementProgramBundle\Entity\ArrangementProgram;
use Pequiven\SEIPBundle\Entity\Period;
use Pequiven\SEIPBundle\Entity\User;
use Pequiven\ArrangementProgramBundle\Entity\Goal;
use Pequiven\SEIPBundle\Doctrine\ORM\SeipEntityRepository as EntityRepository;

/**
 * Repositorio de MOVIMIENTO DE EMPLEADOS
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovementEmployeeRepository extends EntityRepository {

    /**
     * BUSCA EL REGISTRO DE MOVEMENT EMPLOYEE DADO EL USUARIO Y LA META
     * @param type $idGoal
     * @param type $iduser
     * @return type
     */
    function FindMovementIn($idGoal, $iduser, $period) {
        $qb = $this->getQueryBuilder();
        $qb
                ->Select('mov')
                ->andWhere('mov.User = :users')
                ->andWhere('mov.Goal= :goals')
                ->andWhere('mov.out IS NULL')
                ->andWhere('mov.period= :periodo')
                ->setParameter('users', $iduser)
                ->setParameter('goals', $idGoal)
                ->setParameter('periodo', $period)
        ;
        return $qb->getQuery()->getResult();
    }
    
    function FindMovementDetailsbyGoal($idGoal) {
        $qb = $this->getQueryBuilder();
        $qb
                ->Select('movdet')
                ->andWhere('movdet.Goal= :goals')
                ->orderBy('movdet.date')
                ->setParameter('goals', $idGoal)
                
        ;
        return $qb->getQuery()->getResult();
    }

    function getAlias() {
        return 'mov';
    }

}
