<?php

namespace Pequiven\SEIPBundle\Model;

use Doctrine\ORM\EntityRepository;

/**
 * ComplejoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplejoRepository extends EntityRepository
{
}
