<?php

namespace Pequiven\SEIPBundle\Model;

use Doctrine\ORM\EntityRepository;

/**
 * GerenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GerenciaRepository extends EntityRepository
{
}
