<?php

namespace Pequiven\SEIPBundle\Model;

use Doctrine\ORM\EntityRepository;
use Pequiven\SEIPBundle\Entity\Personal;

/**
 * PersonalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalRepository extends EntityRepository
{
    
    /**
     * 
     * @param type $num_personal: Número de Personal
     * @return type
     */
    public function getByNumPersonal($num_personal){
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                    ->select('p')
                    ->from('Pequiven\SEIPBundle\Entity\Personal', 'p')
                    ->where('p.numPersonal = ' . $num_personal)
                    ->getQuery();
        return $query->getResult();
    }
    
}
