<?php

namespace Pequiven\SEIPBundle\Repository\User;

use Pequiven\SEIPBundle\Entity\Period;
use Pequiven\SEIPBundle\Entity\User;
use Pequiven\SEIPBundle\Entity\User\FeeStructure;
use Pequiven\SEIPBundle\Entity\User\MovementFeeStructure;
use Pequiven\SEIPBundle\Doctrine\ORM\SeipEntityRepository as EntityRepository;

/**
 * Repositorio de MOVIMIENTO DE EMPLEADOS
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeeStructureRepository extends EntityRepository {

    function getChildren($idParent) {
        $qb = $this->getQueryBuilder();
        $qb
                ->Select('FeeStr')
                ->andWhere('FeeStr.parent= :Parent')                
                ->orderBy('FeeStr.gerencia')
                ->setParameter('Parent', $idParent)
        ;
        return $qb->getQuery()->getResult();
    }

    function getAlias() {
        return 'FeeStr';
    }

}
