pequiven_seip_arrangementprogram_index:
    path: /.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:indexAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]
    
pequiven_seip_arrangementprogram_list_template:
    path: /list-template.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:listTemplateAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]
    
pequiven_seip_arrangementprogram_assigned:
    path: /assigned.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:assignedAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]
    
pequiven_seip_arrangementprogram_for_reviewing:
    path: /for-reviewing.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:forReviewingAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]
    
pequiven_seip_arrangementprogram_for_approving:
    path: /for-approving.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:forApprovingAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]

pequiven_seip_arrangementprogram_for_notifying:
    path: /for-notifying.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:forNotifyingAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]
    
pequiven_arrangementprogram_create:
    path: /{type}/{associate}/create
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:createAction
        associate: 1
    requirements:
        type: 1|2
        associate: 1|2
    methods: [GET|POST]
    options:
        expose: true
    
pequiven_seip_arrangementprogram_show:
    path: /{id}
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:showAction }
    requirements:
        id: "\d+"
    methods: [GET]
    
arrangementprogram_revised:
    path: /{id}/revised
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:revisedAction }
    requirements:
        id: "\d+"
    methods: [GET]
    
arrangementprogram_return_to_draft:
    path: /{id}/send-to-draft
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:returnToDraftAction }
    requirements:
        id: "\d+"
    methods: [POST]
    
arrangementprogram_return_to_review:
    path: /{id}/return-to-review
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:returnToReviewAction }
    requirements:
        id: "\d+"
    methods: [POST]
    
arrangementprogram_approved:
    path: /{id}/approved
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:approvedAction }
    requirements:
        id: "\d+"
    methods: [GET]
    
arrangementprogram_reject:
    path: /{id}/reject
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:rejectAction }
    requirements:
        id: "\d+"
    methods: [POST]
    
arrangementprogram_send_to_review:
    path: /{id}/send-to-review
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:sendToReviewAction }
    requirements:
        id: "\d+"
    methods: [GET]
    
arrangementprogram_add_observation:
    path: /{id}/add-observation.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:addObservationAction
        _format: json
    requirements:
        id: "\d+"
        _format: json|xml
    methods: [POST]
    
arrangementprogram_update:
    path: /{id}/update
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:updateAction }
    requirements:
        id: "\d+"
    methods: [GET|PUT|POST]
    
arrangementprogram_delete:
    path: /{id}
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:deleteAction }
    requirements:
        id: "\d+"
    methods: [DELETE]
    
arrangementprogram_export:
    path: /{id}/export
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:exportAction }
    requirements:
        id: "\d+"
    methods: [GET]
    
arrangementprogram_start_the_notification_process:
    path: /{id}/start-the-notification-process
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:startNotificationProcessAction }
    requirements:
        id: "\d+"
    methods: [GET]
    
arrangementprogram_finish_the_notification_process:
    path: /{id}/finish-the-notification-process
    defaults: { _controller: pequiven_seip.controller.arrangementprogram:finishNotificationProcessAction }
    requirements:
        id: "\d+"
    methods: [GET]
#SIG
pequiven_seip_arrangementprogram_assigned_sig:
    path: /assigned/sig.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:assignedSigAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]
pequiven_seip_arrangementprogram_for_reviewing_sig:
    path: /for-reviewing/sig.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:forReviewingSigAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]
    
pequiven_seip_arrangementprogram_for_approving_sig:
    path: /for-approving/sig.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:forApprovingSigAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]

pequiven_seip_arrangementprogram_for_notifying_sig:
    path: /for-notifying/sig.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram:forNotifyingSigAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET]
    
pequiven_seip_arrangementprogram_evolution_sig:
    path: /{id}/evolution/{month}.{_format}
    defaults:
        _controller: pequiven.controller.arrangementprogram_sig:evolutionAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]
    
#MOVIMIENTO DE EMPLEADOS
AP_movement:
    path: /mov.{_format}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram_movement:showAPAction
        _format: html
    requirements:
        _format: html|json|xml
    methods: [GET|POST]
    
AP_movement_assign:
    path: /assign/{idAP}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram_movement:assignAction
    methods: [GET|POST]
    options:
        expose: true
        
AP_movement_remove:
    path: /remove/{idAP}
    defaults:
        _controller: pequiven_seip.controller.arrangementprogram_movement:removeAction
    methods: [GET|POST]
    options:
        expose: true